package chiogros.trante.protocols.sftp.ui.ui.screens.connectionedit

import chiogros.trante.protocols.common.CommonConnectionEditFormState

data class SftpConnectionEditFormState(
    override val id: String = String(),
    override var name: String = String(),
    var host: String = String(),
    var user: String = String(),
    var password: String = String(),
    var showPassword: Boolean = false
) : CommonConnectionEditFormState(id = id, name = name) {
    fun copy(
        id: String = this.name,
        name: String = this.name,
        host: String = this.host,
        user: String = this.user,
        password: String = this.password
    ) = SftpConnectionEditFormState(
        id = id,
        name = name,
        host = host,
        user = user,
        password = password
    )

    override fun equals(other: Any?): Boolean {
        if (other !is SftpConnectionEditFormState) {
            return false
        }

        return other.hashCode() == hashCode()
    }

    // Auto-generated by IDE, idk why values are multiplied by 31.
    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + showPassword.hashCode()
        result = 31 * result + id.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + host.hashCode()
        result = 31 * result + user.hashCode()
        result = 31 * result + password.hashCode()
        return result
    }
}