package chiogros.trante.protocols.common

open class CommonConnectionEditFormState(
    open val id: String = String(),
    open var name: String = String()
) {
    open fun copy(id: String = this.id, name: String = this.name): CommonConnectionEditFormState {
        return CommonConnectionEditFormState(id = id, name = name)
    }

    override fun equals(other: Any?): Boolean {
        if (other !is CommonConnectionEditFormState) {
            return false
        }

        return other.hashCode() == hashCode()
    }

    // Auto-generated by IDE, idk why values are multiplied by 31.
    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + name.hashCode()
        return result
    }
}